<center>
    <h1>Procesamiento de datos del Covid-19 en Colombia</h1>
</center>

<h2>
    Autor: Felipe Fernández Rodriguez
</h2>

In [67]:
# Librerías necesarias para el análisis de datos
import pandas as pd

In [68]:
# Librería para definir el path 
import os

# Nombre del archivo
filename = 'Casos_positivos_de_COVID-19_en_Colombia.csv'

# Se define el path
path = os.path.join(os.getcwd(), 'data', filename)

# Cargar el archivo CSV en un DataFrame de pandas
data_covid = pd.read_csv(path)

C:\Users\pipef\AppData\Local\Temp\ipykernel_17944\3090985280.py:11: DtypeWarning: Columns (0: Código ISO del país, 1: Nombre del país) have mixed types. Specify dtype option on import or set low_memory=False.
  data_covid = pd.read_csv(path)

In [69]:
# Visualización del dataframe
data_covid.head()

,fecha reporte web,ID de caso,Fecha de notificación,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Edad,Unidad de medida de edad,Sexo,...,Código ISO del país,Nombre del país,Recuperado,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación,Tipo de recuperación,Pertenencia étnica,Nombre del grupo étnico
0,2020-12-24 00:00:00,"1,556,979",2020-12-22 00:00:00,76,VALLE,"76,001",CALI,67,1,F,...,NaN,NaN,Recuperado,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6.0,NaN
1,2020-12-24 00:00:00,"1,556,980",2020-12-19 00:00:00,76,VALLE,"76,001",CALI,66,1,F,...,NaN,NaN,Recuperado,2020-12-07 00:00:00,NaN,2020-12-23 00:00:00,2020-12-25 00:00:00,Tiempo,6.0,NaN
2,2020-12-24 00:00:00,"1,556,981",2020-12-19 00:00:00,76,VALLE,"76,001",CALI,68,1,F,...,NaN,NaN,Recuperado,2020-12-18 00:00:00,NaN,2020-12-22 00:00:00,2021-01-01 00:00:00,Tiempo,6.0,NaN
3,2020-12-24 00:00:00,"1,556,982",2020-12-22 00:00:00,76,VALLE,"76,001",CALI,74,1,F,...,NaN,NaN,Fallecido,2020-12-17 00:00:00,2020-12-30 00:00:00,2020-12-23 00:00:00,NaN,NaN,6.0,NaN
4,2020-12-24 00:00:00,"1,556,983",2020-12-22 00:00:00,76,VALLE,"76,001",CALI,65,1,F,...,NaN,NaN,Recuperado,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6.0,NaN

In [70]:
# Columnas del df
data_covid.columns

Index(['fecha reporte web', 'ID de caso', 'Fecha de notificación',
       'Código DIVIPOLA departamento', 'Nombre departamento',
       'Código DIVIPOLA municipio', 'Nombre municipio', 'Edad',
       'Unidad de medida de edad', 'Sexo', 'Tipo de contagio',
       'Ubicación del caso', 'Estado', 'Código ISO del país',
       'Nombre del país', 'Recuperado', 'Fecha de inicio de síntomas',
       'Fecha de muerte', 'Fecha de diagnóstico', 'Fecha de recuperación',
       'Tipo de recuperación', 'Pertenencia étnica',
       'Nombre del grupo étnico'],
      dtype='str')

<h3>
    Estandarización de los nombres de las columnas
</h3>

In [71]:
# Se deja el nombre de las columnas en minúscula
data_covid.columns = data_covid.columns.str.lower()

In [72]:
# Se eliminan los espacios por un guión bajo
data_covid.columns = data_covid.columns.str.replace(' ', '_')

In [73]:
# Se quitan las tíldes
data_covid.columns = data_covid.columns.str.replace('ó', 'o').str.replace('í', 'i').str.replace('é', 'e')

In [74]:
data_covid.columns

Index(['fecha_reporte_web', 'id_de_caso', 'fecha_de_notificacion',
       'codigo_divipola_departamento', 'nombre_departamento',
       'codigo_divipola_municipio', 'nombre_municipio', 'edad',
       'unidad_de_medida_de_edad', 'sexo', 'tipo_de_contagio',
       'ubicacion_del_caso', 'estado', 'codigo_iso_del_pais',
       'nombre_del_pais', 'recuperado', 'fecha_de_inicio_de_sintomas',
       'fecha_de_muerte', 'fecha_de_diagnostico', 'fecha_de_recuperacion',
       'tipo_de_recuperacion', 'pertenencia_etnica',
       'nombre_del_grupo_etnico'],
      dtype='str')

In [75]:
# Variables a las que se les va a realizar un conteo de valores del df
variables = ['estado', 'sexo', 'tipo_de_contagio', 'nombre_del_pais', 'tipo_de_recuperacion', 'pertenencia_etnica', 'nombre_del_grupo_etnico']

# Iteración para validar el conteo de valores de cada variable
for var in variables:
    if var in data_covid.columns:
        print(f'{data_covid[var].value_counts(dropna=False)}\n')

estado
Leve         6154791
Fallecido     143125
leve           50623
NaN            41268
Moderado        1056
Grave            106
LEVE               2
Name: count, dtype: int64

sexo
F    3417087
M    2973872
f          6
m          6
Name: count, dtype: int64

tipo_de_contagio
Comunitaria    4447740
Relacionado    1939528
Importado         3703
Name: count, dtype: int64

nombre_del_pais
NaN                            6387253
ESTADOS UNIDOS DE AMÉRICA         1418
MÉXICO                             385
ESPAÑA                             370
BRASIL                             285
                                ...
SAN BARTOLOMÉ                        1
VENEUELA                             1
REPUBLICA POPULAR DEL CONGO          1
REPÚBLICA CHECA                      1
HAITÍ                                1
Name: count, Length: 90, dtype: int64

tipo_de_recuperacion
Tiempo    5274348
PCR        933773
NaN        182398
TIEMPO        452
Name: count, dtype: int64

pertenencia_etnica
6.0    6166659
5.0     137411
1.0      84202
NaN       2156
3.0        405
2.0        138
Name: count, dtype: int64

nombre_del_grupo_etnico
NaN                                                    6307107
Por definir                                              17222
Sin Comunidad                                            12064
ZENU                                                      9264
PIJAO                                                     4112
                                                        ...
COTORRERA-UASPAJURE-SARRUTPANA  ZONA DE WAIMPIRALEN          1
COROZAL                                                      1
PUERTO NARIÑO  -ZONA ASATRIZY                                1
COROCITO                                                     1
MASHALERRAIN                                                 1
Name: count, Length: 1888, dtype: int64

<h3>
    Limpieza de datos de la columna estado
</h3>

In [76]:
# Se define una lista con la cantidad de valores únicos de la columna estado
list_states = list(data_covid['estado'].unique())

# Lista vacía que contendrá los valores únicos en mayúscula
upper_states = []

# Iteración de los estados, transformación a mayúscula y agregación a la lista vacía
for state in list_states:
    upper = str(state).upper()
    if upper == 'NAN':
        upper_states.append('ASINTOMATICO')
    else:
        upper_states.append(upper)

# Se crea el diccionario entre la lista de estados y su respectiva transfomación a mayúsculas
states_dictionary = dict(zip(list_states, upper_states))

# Se realiza el mapeo del diccionario en el df
data_covid['estado'] = data_covid['estado'].map(states_dictionary)

# Se imprime el conteo de valores
data_covid['estado'].value_counts(dropna=False)

estado
LEVE            6205416
FALLECIDO        143125
ASINTOMATICO      41268
MODERADO           1056
GRAVE               106
Name: count, dtype: int64

<h3>
    Limpieza de datos de la columna sexo
</h3>

In [77]:
# Se define una lista con la cantidad de valores únicos de la columna sexo
list_sex = list(data_covid['sexo'].unique())

# Lista vacía que contendrá los valores únicos en mayúscula
upper_sex = []

# Iteración de los sexos, transformación a mayúscula y agregación a la lista vacía
for sex in list_sex:
    upper_sex.append(sex.upper())

# Se crea el diccionario entre la lista de sexos y su respectiva transfomación a mayúsculas
sex_dictionary = dict(zip(list_sex, upper_sex))

# Se realiza el mapeo del diccionario en el df
data_covid['sexo'] = data_covid['sexo'].map(sex_dictionary)

# Se imprime el conteo de valores
data_covid['sexo'].value_counts(dropna=False)

sexo
F    3417093
M    2973878
Name: count, dtype: int64

<h3>
    Limpieza de datos de la columna tipo_de_contagio
</h3>

In [78]:
# Se define una lista con la cantidad de valores únicos de la columna tipo_de_contagio
list_contagion = list(data_covid['tipo_de_contagio'].unique())

# Lista vacía que contendrá los valores únicos en mayúscula
upper_contagion = []

# Iteración de los tipos de contagios, transformación a mayúscula y agregación a la lista vacía
for contagion in list_contagion:
    upper_contagion.append(contagion.upper())

# Se crea el diccionario entre la lista de contagios y su respectiva transfomación a mayúsculas
contagion_dictionary = dict(zip(list_contagion, upper_contagion))

# Se realiza el mapeo del diccionario en el df
data_covid['tipo_de_contagio'] = data_covid['tipo_de_contagio'].map(contagion_dictionary)

# Se imprime el conteo de valores
data_covid['tipo_de_contagio'].value_counts(dropna=False)

tipo_de_contagio
COMUNITARIA    4447740
RELACIONADO    1939528
IMPORTADO         3703
Name: count, dtype: int64

<h3>
    Limpieza de datos de la columna nombre_del_pais
</h3>

In [79]:
# Identifcamos los valores únicos de la columna nombre_del_pais
data_covid['nombre_del_pais'].unique()

<StringArray>
[                                              nan,
                                          'MÉXICO',
                            'REPÚBLICA DOMINICANA',
                                        'ALEMANIA',
                                         'FRANCIA',
                       'ESTADOS UNIDOS DE AMÉRICA',
                                         'ECUADOR',
                                        'PORTUGAL',
                                          'BRASIL',
                                     'EL SALVADOR',
                                          'PANAMÁ',
                          'EMIRATOS ARABES UNIDOS',
                                         'ARMENIA',
                                        'DOMINICA',
                                         'NORUEGA',
                                            'PERÚ',
                                          'ESPAÑA',
                                       'INDONESIA',
                                       'VENEZUELA',
                                           'CHILE',
                               'TRINIDAD Y TOBAGO',
                                       'NICARAGUA',
                                            'PERU',
            'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS',
                                       'ARGENTINA',
                                          'ITALIA',
                                         'CURAZAO',
                                     'PUERTO RICO',
                                          'EGIPTO',
                             'FEDERACIÓN DE RUSIA',
                                          'CANADÁ',
                                       'GUATEMALA',
                                  'ESTADOS UNIDOS',
                                    'ARABIA SAUDÍ',
                                         'TURQUÍA',
                                    'SANTA HELENA',
                                       'BELARUSIA',
 'REINO UNIDO DE GRAN BRETAÑA E IRLANDA DEL NORTE',
                                        'HONDURAS',
                                          'ISRAEL',
                                          'JERSEY',
                                       'AUSTRALIA',
                                      'COSTA RICA',
                                        'PARAGUAY',
                                         'UCRANIA',
                                           'ARUBA',
                                         'JAMAICA',
                                          'LIBANO',
                                         'BOLIVIA',
                    'SAN VICENTE Y LAS GRANADINAS',
                                         'ANDORRA',
                        'REPÚBLICA CENTROAFRICANA',
                                         'URUGUAY',
                                    'PAÍSES BAJOS',
                                            'CUBA',
                                          'SUECIA',
                                         'CAMERÚN',
                                          'PANAMA',
                                  'ARABIA SAUDITA',
                                         'ANGUILA',
                           'REPÚBLICA DOCIMINCANA',
                                       'GUADALUPE',
                                         'ALBANIA',
                                           'KENYA',
                           'ANTILLAS NEERLANDESAS',
                                         'BÉLGICA',
                                       'MARRUECOS',
                                         'IRLANDA',
                                          'GRECIA',
                                           'SUIZA',
                                           'QATAR',
                                       'TABATINGA',
                                         'NIGERIA',
                                          'MEXICO',
                                         'COMORAS',
                                         'CROACIA',
                                         'GRANADA',
                           'REPÚBLICA ÁRABE SIRIA',
                                      'AFGANISTÁN',
                              'POLINESIA FRANCESA',
                              'REPÚBLICA DE COREA',
                                      'MONTENEGRO',
                                     'REINO UNIDO',
                                           'CHINA',
                            'BOSNIA Y HERZEGOVINA',
                                   'SAN BARTOLOMÉ',
                                        'VENEUELA',
                     'REPUBLICA POPULAR DEL CONGO',
                                 'REPÚBLICA CHECA',
                                           'HAITÍ']
Length: 90, dtype: str

In [80]:
# Los valores nulos se van a llenar con el país COLOMBIA, ya que, el contagió no fue importado
data_covid['nombre_del_pais'] = data_covid['nombre_del_pais'].fillna('COLOMBIA')

data_covid['nombre_del_pais'].unique()

<StringArray>
[                                       'COLOMBIA',
                                          'MÉXICO',
                            'REPÚBLICA DOMINICANA',
                                        'ALEMANIA',
                                         'FRANCIA',
                       'ESTADOS UNIDOS DE AMÉRICA',
                                         'ECUADOR',
                                        'PORTUGAL',
                                          'BRASIL',
                                     'EL SALVADOR',
                                          'PANAMÁ',
                          'EMIRATOS ARABES UNIDOS',
                                         'ARMENIA',
                                        'DOMINICA',
                                         'NORUEGA',
                                            'PERÚ',
                                          'ESPAÑA',
                                       'INDONESIA',
                                       'VENEZUELA',
                                           'CHILE',
                               'TRINIDAD Y TOBAGO',
                                       'NICARAGUA',
                                            'PERU',
            'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS',
                                       'ARGENTINA',
                                          'ITALIA',
                                         'CURAZAO',
                                     'PUERTO RICO',
                                          'EGIPTO',
                             'FEDERACIÓN DE RUSIA',
                                          'CANADÁ',
                                       'GUATEMALA',
                                  'ESTADOS UNIDOS',
                                    'ARABIA SAUDÍ',
                                         'TURQUÍA',
                                    'SANTA HELENA',
                                       'BELARUSIA',
 'REINO UNIDO DE GRAN BRETAÑA E IRLANDA DEL NORTE',
                                        'HONDURAS',
                                          'ISRAEL',
                                          'JERSEY',
                                       'AUSTRALIA',
                                      'COSTA RICA',
                                        'PARAGUAY',
                                         'UCRANIA',
                                           'ARUBA',
                                         'JAMAICA',
                                          'LIBANO',
                                         'BOLIVIA',
                    'SAN VICENTE Y LAS GRANADINAS',
                                         'ANDORRA',
                        'REPÚBLICA CENTROAFRICANA',
                                         'URUGUAY',
                                    'PAÍSES BAJOS',
                                            'CUBA',
                                          'SUECIA',
                                         'CAMERÚN',
                                          'PANAMA',
                                  'ARABIA SAUDITA',
                                         'ANGUILA',
                           'REPÚBLICA DOCIMINCANA',
                                       'GUADALUPE',
                                         'ALBANIA',
                                           'KENYA',
                           'ANTILLAS NEERLANDESAS',
                                         'BÉLGICA',
                                       'MARRUECOS',
                                         'IRLANDA',
                                          'GRECIA',
                                           'SUIZA',
                                           'QATAR',
                                       'TABATINGA',
                                         'NIGERIA',
                                          'MEXICO',
                                         'COMORAS',
                                         'CROACIA',
                                         'GRANADA',
                           'REPÚBLICA ÁRABE SIRIA',
                                      'AFGANISTÁN',
                              'POLINESIA FRANCESA',
                              'REPÚBLICA DE COREA',
                                      'MONTENEGRO',
                                     'REINO UNIDO',
                                           'CHINA',
                            'BOSNIA Y HERZEGOVINA',
                                   'SAN BARTOLOMÉ',
                                        'VENEUELA',
                     'REPUBLICA POPULAR DEL CONGO',
                                 'REPÚBLICA CHECA',
                                           'HAITÍ']
Length: 90, dtype: str

In [81]:
# Se crea una lista de los valores únicos de la columna nombre_del_país
countries_list = data_covid['nombre_del_pais'].unique()

# Se crea una lista con los nombres de los paises a corregir
wrong_countries = ['ARABIA SAUDÍ', 'BELARUSIA', 'ESTADOS UNIDOS DE AMÉRICA', 'LIBANO', 'MEXICO', 'PANAMA', 'PERU', 'REINO UNIDO DE GRAN BRETAÑA E IRLANDA DEL NORTE', 'REPÚBLICA DOCIMINCANA', 'SANTA HELENA', 'TABATINGA', 'VENEUELA']

# Se crea una lista con los nombres de los paises correctos
right_countries = ['ARABIA SAUDITA', 'BIELORRUSIA', 'ESTADOS UNIDOS', 'LÍBANO', 'MÉXICO', 'PANAMÁ', 'PERÚ', 'REINO UNIDO', 'REPÚBLICA DOMINICANA', 'REINO UNIDO', 'BRASIL', 'VENEZUELA']

# Se crea la lista vacía que contendrá los valores correctos
new_countries_list = []

# Se realiza la iteración de las listas para llenar la lista que contendrá los valores correctos
for country in countries_list:
    if country in wrong_countries:
        new_countries_list.append(right_countries[wrong_countries.index(country)])
    else:
        new_countries_list.append(country)

# Se crea el diccionario entre la lista de paises y su respectiva transfomación
country_dictionary = dict(zip(countries_list, new_countries_list))

# Se realiza el mapeo del diccionario en el df
data_covid['nombre_del_pais'] = data_covid['nombre_del_pais'].map(country_dictionary)

# Se imprime el conteo de valores
data_covid['nombre_del_pais'].value_counts(dropna=False)

nombre_del_pais
COLOMBIA                       6387253
ESTADOS UNIDOS                    1424
MÉXICO                             386
ESPAÑA                             370
BRASIL                             293
                                ...
BOSNIA Y HERZEGOVINA                 1
SAN BARTOLOMÉ                        1
REPUBLICA POPULAR DEL CONGO          1
REPÚBLICA CHECA                      1
HAITÍ                                1
Name: count, Length: 80, dtype: int64

<h3>
    Limpieza de datos de la columna tipo_de_recuperacion
</h3>

In [82]:
# Visualización de los valores unicos de la columna tipo_de_recuperacion
data_covid['tipo_de_recuperacion'].unique()

<StringArray>
['Tiempo', nan, 'PCR', 'TIEMPO']
Length: 4, dtype: str

In [83]:
# Se define una lista con la cantidad de valores únicos de la columna recovery_dictionary
list_recovery = list(data_covid['tipo_de_recuperacion'].unique())

# Lista vacía que contendrá los valores únicos en mayúscula
upper_recovery = []

# Iteración de los tipos de recuperación, transformación a mayúscula y agregación a la lista vacía
for recovery in list_recovery:
    upper = str(recovery).upper()
    if upper == 'NAN':
        upper_recovery.append('NO RECUPERADO')
    else:
        upper_recovery.append(upper)

# Se crea el diccionario entre la lista de tipos de recuperación y su respectiva transfomación a mayúsculas
recovery_dictionary = dict(zip(list_recovery, upper_recovery))

# Se realiza el mapeo del diccionario en el df
data_covid['tipo_de_recuperacion'] = data_covid['tipo_de_recuperacion'].map(recovery_dictionary)

# Se imprime el conteo de valores
data_covid['tipo_de_recuperacion'].value_counts(dropna=False)

tipo_de_recuperacion
TIEMPO           5274800
PCR               933773
NO RECUPERADO     182398
Name: count, dtype: int64

<h3>
    Limpieza de datos de la columna pertenencia_etnica
</h3>

In [84]:
# Visualización de los valores unicos de la columna pertenencia_etnica
data_covid['pertenencia_etnica'].value_counts(dropna=False)

pertenencia_etnica
6.0    6166659
5.0     137411
1.0      84202
NaN       2156
3.0        405
2.0        138
Name: count, dtype: int64

In [85]:
# Se llenan los campos nulos con el número 4 que es el indicador faltante
data_covid['pertenencia_etnica'] = data_covid['pertenencia_etnica'].fillna(4)

# Se imprime el conteo de valores
data_covid['pertenencia_etnica'].value_counts(dropna=False)

pertenencia_etnica
6.0    6166659
5.0     137411
1.0      84202
4.0       2156
3.0        405
2.0        138
Name: count, dtype: int64

In [86]:
# Se transforman el código de la pertenencia étnica por el nombre correspondiente
data_covid['nombre_pertenencia_etnica'] = data_covid.apply(lambda row: 
    'INDIGENA' if row['pertenencia_etnica'] == 1
    else 'ROM' if row['pertenencia_etnica'] == 2
    else 'RAIZAL' if row['pertenencia_etnica'] == 3
    else 'PALENQUERO' if row['pertenencia_etnica'] == 4
    else 'NEGRO' if row['pertenencia_etnica'] == 5
    else 'OTRO' if row['pertenencia_etnica'] == 6
    else row['pertenencia_etnica'], axis=1 
)

#Se eliminan la columna pertenencia_etnica
del data_covid['pertenencia_etnica']

# Se imprime el conteo de valores
data_covid['nombre_pertenencia_etnica'].value_counts(dropna=False)

nombre_pertenencia_etnica
OTRO          6166659
NEGRO          137411
INDIGENA        84202
PALENQUERO       2156
RAIZAL            405
ROM               138
Name: count, dtype: int64

<h3>
    Limpieza de datos de la columna nombre_del_grupo_etnico
</h3>

In [87]:
# Visualización de los valores unicos de la columna nombre_del_grupo_etnico
nombre = data_covid['nombre_del_grupo_etnico'].unique()
str_name = [str(name) for name in nombre]
str_name = sorted(str_name)

for name in str_name:
    print(name)

'CHAPARRAL
1
13 DE MAYO
17 DE JUNIO
7 DE AGOSTO
8 DE DICIEMBRE
ACARICUARA - ZONA AZATIAC
ACEVEDO Y GOMEZ
ACHAGUA
ACHIOTE
ACO VIEJO-PATIO BONITO
AGUA CLARA
AGUA CLARITA
AGUA NEGRA
AGUABLANCA
AGUACAT BUYESH
AGUAS CLARAS
AGUAS VIVAS
AGUASAL ZONA 1
AGUAZUL
AICO
AIMA
AIPIACHI
AIPIOLARAIN
AL JOTE
ALAINAPA
ALDEA DE MARIA
ALEWA LOS MONOS
ALGARROBO
ALGODONCILLO
ALIRAPA
ALITAJAIN
ALITAMANA CASUSHY
ALMENDRO
ALNAMAWAMI
ALPAMANGA
ALPES ORIENTALES
ALPHA TUM SACHA
ALTA RIVERA ROMA
ALTAMIRA
ALTAMIRA CANANARI - ZONA ACTIVA
ALTO ALBI
ALTO ARMADA
ALTO CARDOZO
ALTO CARTAGENA
ALTO COMBOY
ALTO EL PALMAR
ALTO LORENZO
ALTO MANGUITO
ALTO MUIDO ZONA 4
ALTO NAPO RUNA
ALTO SANTANA
ALTO SUSPIZACHA
ALTO TEMBLON
ALTOPLANO SAN ANTONIO
ALUATAPAY
ALUICIRA (ALUISIRRA)
AMAICHON III
AMAICHON SECTOR SABANA
AMAIKULE
AMARIJUNA
AMBACHEKE
AMBALO
AMBIKA
AMENANI
AMOYA LA VIRGINIA
AMPARRADO GRANDE
AMUCHEN
AMUCHISHIGOU
AMULAMANA
AMURULUBA
AMUSHICHOW (AMUSHISHOU)
AMUTKOU
ANABA
ANACARCO
ANARALITO NUEVO
ANAYACO DE LOS ANDAQUIES
ANCESTROS COYA MANAGRANDE TERRITORIO SAGRADO
ANDAKIES
ANDES NORTE
ANDOKE
ANDOQUE DE ADUCHE
ANGOSTURA
ANSEA
ANUACHON JULIAKAT
ANYINAKAL
APALASCHON
APARCO
APATALAIN ( ZONA WIMPESHI)
APONTE
APOTOLURU
APUNIMANA
ARACHE
ARAGUATO
ARANGUANSIRA
ARAPAREN
ARAPU
ARARA
ARARA-CUDUYARI UDIC
ARAUCA
AREMASAIN
ARENA
ARENAL
ARENALITO
ARENOSA
ARHUACO
ARHUACO DE LA SIERRA NEVADA
ARITAIMANA
ARQUIA
ARROYO DEL MEDIO
ARROYO LIMON
ASIJUSHEIN
ASOCIACION NATIVA
ATACHONCAT
ATAMANA
ATANQUE
ATAPU
ATATOW
ATNAMANA
ATOULIA
ATPANAPOU
ATPATSIMA
ATURAIMPA
ATUSCHOUN
ATUTULI
AUKAWASI
AULAULIA
AWA
AWA IM
AWA LA UNION LA DORADA
AWA SEVILLA
AWA TATCHAN
AWALIBA CENTRAL
AYWJAWASHI EL JORDAN
BABILONIA
BACATI
BACURI
BAJO CARDOZO
BAJO CASACUNTE
BAJO CURRIPIPI ZONA 1
BAJO DE LATA
BAJO GRANDE
BAJO NORTE
BAJO OSTION
BAJO PALMITAL
BAJO REMANSO
BALOCA
BALSILLAS
BALSILLAS LIMON
BANDERA
BANGA-ITA
BANGAÑITA
BANIVA
BARBACOA
BARBACOAS
BARI
BARRANCO COLORADO-ZONA UDIC
BARRANQUILLA
BARRO PRIETO
BARROSA
BARZALOZA
BATEAS
BATROCTRORA
BECARPIGAR
BELEN
BELLA ISLA
BELLA VISTA
BELLAVISTA
BELLAVISTA DE ABIYU - AATIZOT
BELLAVISTA RECUPERACION
BELTRAN
BERGEL
BERLIN
BETANIA
BIAKIDURE
BLEO BERDINAL
BOCA DE JARRO
BOCANAS DE LUZON
BOCAS  DEL YI-ASATRAIYUVA
BOCAS DE ARARA
BOCAS DE HILARCO
BOCAS DE KUMEJ
BOCAS DE LA RAYA
BOCAS DE URE
BOCAS DEL TETUAN
BOCAS DEL YI ZONA AZATRAIYUVA
BOCOA QUERARI - ZONA ASATIQ
BOCON BETULIA
BOCOTA
BORA
BOSSA NAVARRO
BOTOCHERRAIN
BRILLANTE NORTE
BRISAS
BRISAS DE ATA
BRISAS ZONA 4
BUENA VISTA
BUENA VISTICA
BUENAVISTA
BUENAVISTA MECHE
BUENOS AIRES
BUENOS AIRES ABAJO
BUENOS AIRES CANANARI ZONA ACTIVA
BUENOS AIRES GILGAL
BUENOS AIRES NORTE EL CHUZO
BUENOS AIRES SUR
CA-O BACHACO
CA-O GUARIPA
CABECERA MUNICIPAL
CABILDO CARDON
CABILDO CARRIZAL
CABILDO LA PAZ
CACAHUAL
CACAOTAL
CACHACA II PAINWASHI
CACHIVERA-ZONA OZCIMI
CACHUYAS
CACIQUE YAIMA
CAFE PISAO
CAICEDONIA
CAIR
CAIRONARE
CAISAM
CAJON DE MACULE
CALAFITAS I
CALAPENA
CALARA SAN MARTIN
CALARCA
CALDERAS
CALIENTE
CALLE DEL MEDIO
CALLE LARGA
CALLE RALITA
CAMAINKIBO INGA KICHWA
CAMANAOS - ISANA
CAMENTSA BIYA
CAMENTSA BIYA DE ORITO
CAMENTSA INGA
CAMINO REAL
CAMPAMENTO
CAMPAMENTO-KARRAPUZER-PALMASOL
CAMPANA
CAMPO ALEGRE
CAMPO BELLO
CAMPO BELLO AWA
CAMPO BELLO PASTOS
CAMPO FLORIDO
CAMPO LAS MIRELLAS
CAMUTI-ZONA UDIC
CANALI VENTAQUEMADA
CANEGUACAT
CANEWAKAY
CANGREJO
CANIME
CANOAS
CANTAGALLO
CAPICHIRAULE
CAPIRRA
CAPITANIA
CARACOL
CARACOLI
CARANACOA
CARI CAR II
CARIACHIL
CARIJONA
CARIYUSEN MASHALERRAIN
CARIÑITO
CARLOSAMA
CAROLINA
CARPINTERO
CARRAIPIA
CARRANGUERO
CARRANZO
CARRAZAL
CARRETAL
CARRIZAL
CARROUYACHON
CARTAGENITA
CARTAMA
CARURU
CARURU QUERARI ZONA ASATIQ
CASA DE ZINC
CASA ELECTRICA
CASCAJAL
CASCAJERO ZONA 4
CASHUSHUJUNA
CASITAS ARGENTINA
CASTILLA ANGOSTURAS
CASTILLA ANONALES
CASTILLERAL
CASTILLETE CLAN EPINAYU
CASUSO
CASUTALAIN
CATAMBUCO
CATANACUNAME
CATUFA
CAURA
CAURACIRA
CAUROMA (CERRO TACON)
CAÑA BRAVA
CAÑADUZALES
CAÑAVERAL
CAÑO GUARIPA
CAÑO LA HORMIGA
CAÑO NEGRO
CAÑO RAYA
CAÑO VIÑA
CAÑON DEL RIO PEPITAS
CECILIA COCHA
CEDRAL
CEDRALES PERALONSO
CEIMA CACHIVERA ZONA AATIAM
CEIWACAT
CEIWAKAT LOS CARDONALES
CELESTE IMPERIO
CEMENTAMANA
CEMENTEMANA
CENEGAL
CENTRO ALEGRE
CENTRO AMERICA
CENTRO CARDOZO
CENTRO CHORRERA
CENTRO DE TARAPACA
CENTRO MIRAFLORES
CENTRO OIYAKA
CERRITO DE LA PALMA
CERRO
CERRO ALTO CLAN EPIAYU
CERRO BOMBA
CERRO DE PAJA
CERRO DEL NARANJO
CERRO GUADUA
CERRO VIDALES
CERRODEO
CEURA
CEVEDE ZONA 1
CHACHAJO
CHANU
CHANUL
CHAPA
CHAPARRAL
CHAPARRAL Y BARRO NEGRO
CHAPINERO LOANY TOY
CHAQUIRA
CHAQUITA
CHARCO CAIMAN
CHELEVA (POZO AZUL)
CHENCHE AGUA FRIA
CHENCHE AMAYARCO
CHENCHE ANGOSTURA
CHENCHE ASOLEADOS
CHENCHE ASOLEADOS- EL VERGEL
CHENCHE BALSILLAS
CHENCHE BUENAVISTA
CHENCHE BUENOS AIRES INDEPENDIENTE
CHENCHE BUENOS AIRES TRADICIONAL
CHENCHE MEDIA LUNA
CHENCHE SOCORRO  LOS GUAYABOS
CHENCHE TUNARCO
CHENCHE ZARAGOZA
CHICALA PIJAO
CHICHITUY
CHICORA
CHICUAMBE LAS BRISAS
CHIMA URBANO (CABECERA MUNICIPAL)
CHINGUIRITO MIRA
CHINU URBANO
CHIQUINIMA
CHIULIAPA
CHIVARAQUIA
CHOCHO
CHONCOMANA
CHORETCHON
CHORRILLO
CHORROISIRRA
CHOTCHOSIRRA-WALULE-YARRALEEN-MUCHICHEN
CHUNUWOU-ALPATRE-ISHASTU-ISHIWOU-MALIPICHIRRA-SARRUTPANA
CHUPUNDUN
CHURRUIPANA
CIBARIZA
CIENAGUITA
CIMARRONA ALTA
CIMPAMANA - IRUAN
COAYARE
COBARIA
COCAMA
COCANA
COCHORRETAMANA
COCO VIEJO
COCOMANA
COCONUCO
COEMANI
COFRADIA
COLONSUAMANA-MACULUBO-JUALITA
COLOYA
COMEJEN
COMERCIO
COMUNIDAD BELLO HORIZONTE DORADA
COMUNIDAD EL PEÑON
COMUNIDAD MUISCA COTA
COMUNIDAD MUISCA SESQUILE
COMUNIDAD PUERTO NUEVO
COMUNIDAD VILLA PORVENIR
CONCORDIA
CONDAGUA
CONONDO  ZONA 1
CONSARA MECAYA
CONSEJO DE ANCIANOS
CONTENTO
CORDILLERA
COREGUAJE
COROCITO
COROCITO  YOPALITO WACOYO
COROZAL
COROZAL 2 (TROMPILLO)
COROZAL UNO
COROZALITO
CORRAL DE SAN LUIS
COSTA DE ORO
COSTA RICA
COTORRERA-UASPAJURE-SARRUTPANA  ZONA DE WAIMPIRALEN
COTOYRAI
COUSEPA
COUSHARIPA
COYARCO
CRIS (REMANSO INDOSTAN SOLEDAD)
CRISTALES CHORRERA BLANCA
CRISTALINA II
CRUCITA LA VIRGINIA
CRUZ CHIQUITA
CRUZ DE MAYO
CRUZ DEL BEQUE
CRUZ DEL GUAYABO
CUAIQUER VIEJO
CUAMANA
CUASBIL LA FALDADA
CUATRO BOCAS
CUATRO VIENTOS
CUBAY - ZONA OZCIMI
CUBEO
CUCHARO SAN ANTONIO
CUCHILLA PALMAR
CUCURA ZONA OZCIMI
CUCURITAL
CUENCA DEL RIO GUABAS
CUERVO ARAOZ - ZONA OZCIMI
CUESTA ABAJO
CUIBA
CUIVA-CA-O VIEJO
CUIVA-CAÑO VIEJO
CUMARALITO
CUMBAL
CUNA
CURARE
CURRIPACA
CURRIPACO
CURTIRAPLEKA
CUSAY O LA COLORADA
CXHAB WALA LUUCX-BELLO HORIZONTE
DACHI DRUA
DAMASCO VIDES
DANTO
DESANO
DIAMANTE
DIMAS O´NEL MAJIN
DIVIDIVI -CORREGIMIENTO DE EL CARDON
DIVINO NIÑO
DOCE DE OCTUBRE ZONA OZCIMI
DOMINICO
DOPANAE
DOUJURAVIDA
DOYARE CENTRO
DOYARE PORVENIR
DOYARE RECRISTO
DUJOS_TAMAS
DXI´ U´SE (ANTES CXHAB WALA)
E
EBANO TACANAL
EDEN
EIRRATAMANA
EKIMANA
EL ARROYO 1
EL BANCO
EL BOLAO-LAS ESTANCIAS
EL BRILLANTE LA BALASTRERA
EL BUGRE
EL CAMPANO DE LOS INDIOS
EL CANAL
EL CARITO
EL CARMEN DE PETACA
EL CASTA-AL
EL CASTAÑAL
EL CEDRO LAS PEÑAS LA BRAVA PILVI Y LA PINTADA
EL CRUCERO
EL DANUBIO - NASA KWUMA TEWESX
EL DELIRIO
EL DESCANSO
EL DIVIDIVI
EL DUYA
EL ENCANTO
EL ESCOBAL
EL ESTERO
EL FLORAL
EL GRAN SABALO
EL HACHA
EL HOYAL
EL LIMONCITO (RI A Y M)
EL LLANO
EL MAIZAL
EL MAMEY
EL MAMON
EL MANGO
EL MANGUITO
EL MARTILLO
EL MEDANO
EL MOLINO
EL MORA
EL OLIVO
EL OSO
EL PALMAR
EL PALMAR - ASATAV
EL PANDO
EL PARAISO
EL PASITO
EL PEINE
EL PITAL
EL PIÑAL
EL PORVENIR
EL PRINCIPIO
EL PROGRESO
EL QUINCE
EL RECUERDO-ZONA OZCIMI
EL REDENTOR DEL MARAÑONAL
EL REMANSO
EL REPARO
EL RETIRO
EL ROBLE
EL ROSAL
EL SALADO
EL SANDE
EL SANTUARIO
EL TABLERO
EL TAMBO
EL TIGRE
EL TRIUNFO
EL VERGEL
EL VOLAO
EMBERA
EMBERA CHAMI
EMBERA CHAMI GUATICA
EMBERA CHAMI QUINCHIA
EMBERA KATIO
EPERARA SIAPIDARA
EQUIACAL
EQUIAKAL
ESCOBALITO
ESCOBAR ABAJO
ESCOBAR ARRIBA
ESCOPETERA Y PIRZA
ESMERALDA NORTE
ESMERALDA SUR
ESPINALITO
FINZENU DE SAN SEBASTIAN
FINZENU MARCIAL ALEGRIA DE SAN SEBASTIAN
FIW PAEZ
FLECHA
FLECHA SEVILLA
FLOR DE LA GUAJIRA
FLOR DE LA SABANA
FLOR DEL MONTE
FLORAL TRADICIONAL
FLORES DE MOCHA
FRONTINO
FUENTE DE VIDA
FUKUANAE
GALAPA
GAMBOTE
GARCIAMANA
GARDENIAS
GARRAFA-ZONA UDIC
GEGORA QUIPARA MURANDO TIRAVENADO Y JUGUADO
GEMEMAHS-KURAPULEN-JUYUMANA
GENGADO PORROSO
GERARDO VALENCIA CANO- ZONA OZCIMI
GETUCHA
GRAN PUTUMAYO
GRAN TESCUAL
GRANATES
GRASAMANA
GUACAMAYO DE ARARACUARA
GUACARI
GUACHICONO
GUACO BAJO
GUADUALEJAS
GUADUALITO
GUAGUARCO PALMAROSA
GUAIMARAL
GUAIMARITO CLAN GUAURIYU
GUAIMARITO CLAN PUSHAINA
GUAIMARITO CLAN URIANA
GUAIMARO
GUAIMI
GUAIMPLETU
GUAINAP
GUAIPA CENTRO
GUAIPA UNO
GUALERAS
GUALIRUMANA
GUALON
GUAMACHITO CLAN EPIAYU
GUAMACHITO CLAN GOURIYU
GUAMACHITO CLAN GUAURIYU
GUAMACHITO CLAN IPUANA
GUAMACHITO CLAN PUSHAINA
GUAMITO
GUANAKAT
GUANANO
GUANAPAIMANA
GUARAPAMBA
GUARMI IMA
GUARPANA
GUASIMAL
GUATAVITA TUA
GUATPULIGUOU
GUAVIARE
GUAVIO FLAUTILLO
GUAYABAL
GUAYABERO
GUAYABO SUR
GUAYACANES NORTE
GUAYACANES SUR
GUAYACASIRA
GUAYAQUIL
GUAYAQUIL LOS PIJAOS
GUELNAMBI CARAÑO
GUYTICHON
HAIMANA
HALAMATKAT
HEMIMANA
HEREDEROS DE TABACO COCA Y YUCA DULCE CIHTACOYD P + + NE ABYEJU + JTSAMEI
HERMEREGILDO CHAKIAMA
HILARQUITO
HIOTSHY
HIRTU
HITNU
HOJA ANCHA
HONDA RIO GUIZA
HUARE - HUAREN
HUELLAS
HUERTAS CHICAS
HUERTAS CHICAS ARRIBA
HUESO
HUILA
HURRAICHICHON
HURTADO
HUTAPO
IBACABA - ACAZUNIP
ICHIPANA
ICHITU
ICHIYEN
ICO VALLE DE ANAPE
ILES
IMBA
INCHUCHALA MIRAFLORES
INDA GUACARAY
INDA ZABALETA
INGA
INGA DE BOGOTA
INGA DE COLON
INGA DE MOCOA
INGA DE SAN ANDRES
INGA DE SANTIAGO
INGA JOSE HOMERO
INGA KAMSA
INGA NUNA RUMI
INGA SAN PEDRO
INGA SUMA YUYAY SIGNO CARMELO
INKAL WATZAL
INTI YAKU
INTILLAGTA HIJOS DEL SOL
IPAIN
IPAMANA
IPAPURE
IPASHIRRAIN
IRRUALU
IRRUAPA
IRRUWAIN
IRRUWALA
ISHAIN
ISHAMANA
ISHAPA
ISHIPAA
ISHORSHIMANA
ISHOTSHIMANA
ISHU AWA
ISHUSIMANA
ISIRAIN
ISLA DE RONDA
ISLA GALLINAZO
ISMUINA
IYULIWOOU
JABALCON
JAGUAL
JAI ZIAYA BAIN
JAIKA-KALINCHON
JAIKERAZAVI
JAIPAREIM
JAIPAREN
JALAJATSHITU
JALALAO
JALESAPATU
JAMBALO
JAMPUSUMANA
JAR
JARAIPA
JARESAPAIN
JARIYE
JASACHON
JASAIKA (GUADALUPE)
JASAIKA GUADALUPE (CORREG. MUSICHI SECTOR YAWAKA)
JASAIKAT JARALAKAT AGUAKAURI (ZONA CERRO DE LA TETA)
JASALEECHON
JASALIMA KM 80 VIA CARRAIPA
JASAYKA-JARALAKAT-AGUAKAURI
JATKUSIRRA
JATTO (KILOMETRO 30 VIA ALBANIA)
JAYARIMA
JAtENI DtONA PORTAL FRAGUITA
JEBALA
JEGÜITA
JEJEN
JELLUPURE
JENOY
JEPIMANA
JER JET
JERUSALEN
JETSU
JE´ERURIWA YUCUNA
JICHITKA
JIKARU
JIMULASHI (ZONA JOJONCITO)
JIRIJIRI
JIRRUMANA
JISEMANA
JIWARAIN
JIW_GUAYABE
JIW_GUAYABERO
JOCOTOLIWOU-CALULIWOLI-MOCHOMANA-JULUANOUL
JOLONOLUWO
JOTOMANA
JUAN TAMA
JUARUCO
JULIAN PEREZ
JULLAMANA
JULLANASPA- ZONA POPORTIN- CORREGIMIENTO CARDON
JUNUNTAO
JUPECHIMANA
JURRALEN
JURRASQUERA
JURRULAPIA
JURUJURAMANA
JURULUBAN LAS AMERICAS
JUSY MONILLA AMENA KM 9
JUYARARPANA
JUYASIRAIN
KACTOULUMANA
KAIKAISHI
KAITAMANA (ZONA CARRIZAL)
KAITAMANA (ZONA JONJONCITO)
KAIWARRAIMANA (SECTOR POPORTIN- CORREGIMIENTO DE CARDON))
KAIWARRAIMANA (SECTOR POPORTIN_ CORREGIMIENTO DE CARDON)
KALAIPIOU
KALANSHIRRA
KALARKA
KALINATAIN
KALIWIRNAE
KAMENTSA
KAMENTSA BIYA DE SIBUNDOY
KAMUSCHIPA
KANALITOJO
KANKUAMO
KARAMBA
KAREKAREMANA
KARIJONA
KARIKACHABOQUIRA
KARIMAYA-PERRAWOU-JASHIEMANA
KARRIZAL
KASICHI
KASIPAICHI (KASUMANA)
KASIRRUMAI (SIERRA MAESTRA)
KASISCHON
KASISKA
KASIWOLAIN (KASIWORIN) ZONA MEDIA LUNA- COREGIMIENTO CABO DE LA VELA
KASUSAIN
KASUSHI
KATANAMANA
KATURALINCE
KATZALIAMANA UNO
KAUCHACHON
KAUCHIRRAWAPO ZONA CARDON
KAUWAMANA
KAYUHUO
KAYUSWARAALU ZONA DE LOS COCOS
KAYUSWARAALU_ ZONA DE LOS COCOS_ CORREGIMIENTO BAHIA HONDA
KEMERRIARU
KEREZIAMANA
KERRARIAMANA (ZONA JONJONCITO- CORREGIMIENTO JONJONCITO)
KERRARIAMANA (ZONA JONJONCITO_ CORREGIMIENTO JONJONCITO)
KICHWA
KICHWA DE SESQUILE
KILOKA PLAYA VERDE
KIOSCO
KIPARA ZONA 1
KITEK KIWE
KIZGO
KOFAN
KOGUI
KOGUI MALAYO ARHUACO
KOJORROMANA
KOKONUCO
KOLOYOSU
KOOSHIMANA
KOTORRERUMANA
KSXAW NASA
KUISARU
KULAALANCHI
KULESIAMANA
KURAK CHAK
KUTIMPA
KWESX KIWE
KWESX UMA KIWE (NUESTRA MADRE TIERRA)
LA  SOLEDAD
LA 18
LA ASUNCION
LA BANDERAS
LA BONANZA
LA CEIBA
LA CHONTA EL CHIRCAL
LA CILIA O LA CALERA
LA CONCEPCION
LA CRISTALINA
LA CUMBRE
LA ESMERALDA DE CHOCHO
LA ESMERALDA DE COLOSO
LA ESPERANZA
LA ESTACION TALAGA
LA ESTRELLA
LA ESTRELLITA
LA FLECHA ALTOZANO
LA FLORESTA
LA FLORESTA ALTO COQUETO
LA FLORESTA JAIDE
LA FLORESTA LA ESPAÑOLA
LA FLORESTA PACA - ZONA AZATIAC
LA FLORIDA PIRACUARA PAPURI -ZONA ACAZUNIP
LA FUGA
LA GAITANA
LA GALLERA
LA GLORIA
LA GLORIA N° 2
LA GRANJA
LA ISLA
LA LAGUNA
LA LAGUNA LA SIBERIA
LA LIBERTAD
LA LIBERTAD ( FXIW KSXAW WALA)
LA LIBERTAD PICA PICA VIEJO
LA LOMA
LA LOMITA CLAN JAYARIYU
LA LUCHA
LA LUCHA Y EL CACAO
LA LUISA
LA MARIA
LA MONTAÑA
LA MORENITA
LA NUEVA ESPERANZA
LA PAILA NAYA
LA PALMIRA
LA PAYA
LA PAZ
LA PE-ATA
LA PEÑATA
LA PICHE
LA PISTA
LA PLAYA
LA PLAYA ALTO NAYA
LA PORFIA
LA PRIMAVERA II ETAPA
LA RAYA
LA REFORMA
LA REFORMA ALTO SAN MIGUEL
LA RIVERA
LA ROCHELA
LA SABANA ZONA OZCIMI
LA SABANA-CUBIYU -ZONA AATIVAM
LA SABANA-ZONA OZCIMI
LA SALINA
LA SIERPE
LA SIRIA
LA SORTIJA
LA TAMBORA
LA TATACOA
LA TOLDA
LA TRINA
LA TUNA SECTOR MUSICHY
LA TURBIA
LA TUTIRA BONANZA
LA UNION
LA UNION FLORESTA
LA VENTA LA ESPERANZA
LA VILLA
LACANTAMANA
LAGARTO COCHA
LAGO GRANDE
LAGOS DEL DORADO
LAGUNA MOROCOTO
LAS BRISAS
LAS CASITAS SUR
LAS CAVERNAS
LAS CRUCES
LAS DELICIAS
LAS DELICIAS (KIWE ÑXUSXA)
LAS FLORES LA GALLERA
LAS HUERTAS
LAS LOMAS
LAS MARIAS
LAS MERCEDES
LAS PALMAS
LAS PALOMAS EL OLIVO
LAS PEÑITAS
LAS PIEDRAS
LAS PILAS
LAS VILLAS
LIBERTAD - ZONA OZCIMI
LIMONAR
LLANO BUCO  BUKJ UKUE
LLANOS DE YARI  YAGUARA II
LLOVEDERO
LOCOMBOO
LOMA ALTA
LOMA BAJA
LOMA DE PIEDRA
LOMA DE TIGRE BUENOS AIRES
LOMA FRESCA
LOMA LINDA
LOMAMATO CLAN EPIAYU
LOMAMATO CLAN GOURIYU
LOMAMATO CLAN PUSHAINA
LOMAS DE GUACARCO
LOMAS DE HILARCO
LOMAS DE PALITO
LOMAS MESA DE SAN JUAN
LORICA ZENU VEREDA NUEVA ESPERANZA
LOS ALGARROBOS
LOS ALMENDROS
LOS ALTOS
LOS ANGELES
LOS ANGELES - PAPURI-UNIZAC
LOS BAOS
LOS CALEÑOS
LOS CARRETOS
LOS CASTILLOS
LOS CERROS
LOS CORREA
LOS GAVIRIA
LOS GUADUALES
LOS INGLESES BORICADA
LOS MANANTIALES
LOS MANGOS
LOS POIMAS
LOS VENADOS
LOVERAN
LUCERITO ALTO
LULUMOY
LUSITANIA
LUTAKA
MACAHUAN
MACEDONIA
MACO CALARMA
MACOCOBA
MACUCICHON
MACUCU-ASATRIVBA
MACUREMA
MACURIPANA UNO
MAGILY
MAICHERRU
MAIKAITO
MAIZ
MAJAGUAL
MAJAGUAL No 1
MAJAGUAL No. 2
MAJALI
MAJAYULUMANA
MAJAYURA
MAJAYUTPANA
MAKU
MAKULANTIRRA
MAKURRUIPIA
MALA NOCHE
MALANQUE
MALAWAIKATH
MALEEN-MAISHIPA-WOUPASE
MALEMBA
MALUAIZAO
MAMATOCO
MAMURA
MANALEN
MANGAL
MANGAL 1
MANGUITO
MANICA
MANNARIPA
MAPAJIWOU
MAPUAIN SECTOR CARDON
MAPUAMANA
MAQUINAC
MARA-AMANA (ZONA PARAISO_ CORREGIMIENTO PARAISO)
MARACARY
MARAÑAMANA (ZONA PARAISO- CORREGIMIENTO PARAISO)
MARAÑAMANA (ZONA PARAISO_ CORREGIMIENTO PARAISO)
MAREIGUAMANA
MARIWAKY
MAROUJELLA
MARROYAMANA
MARTIN ROQUEME
MARUZA
MASAMANA
MASEN
MASHALERRAIN
MASHI
MASHIICHON ANTES BUENOS AIRES
MASUREN
MATA DE CAÑA
MATANEGRA
MATAPI
MATECANDELA
MATEO PEREZ
MATICURU
MATORA DE MAITO
MATRACA
MAURIPAO
MAWASIRRA
MAYALITA
MAYAPO
MAÑATUY
MECHE SAN CAYETANO
MECHUAMANA
MECOLOMANA
MEDIA LUNA (SECTOR WIMPESHI_ CORREGIMIENTO WIMPESHI)
MEDIA SOMBRA
MEIRA
MERCADILLO
MEREY
MERRATUSHI
MERRUNAIN
MESA DE CUCUANA ACEITUNO
MESA DE CUCUANA SANTA RITA
MESA DE ORTEGA
MESA DE POLE
MESAS DE INCA
MESAS DE SAN JUAN
MESONES
META TERRITORIAL
MEXICO
MEZAMANA
MI RANCHITO
MILAN
MINITAS
MIRA-A
MIRAFLOR
MIRALEJO
MIRALINDO
MIRAMAR
MIRAÑA
MIROLINDO
MISAK_GUAMBIANO
MITUSEÑO - ZONA AATIAM
MOCAGUA
MOCHOMANA
MOCHUELO
MOCONDINO
MOCUMANA
MOHAN CUATRO VIENTOS
MOISPA (SECTOR MEDIA LUNA)
MOJARRITA ZONA 2
MOKANA
MOKANA DE BARANOA
MOKANA DE GALAPA
MOKANA DE MALAMBO
MOKANA DE PUERTO COLOMBIA
MOLINA
MOMIL URBANO
MOMPOX
MONFORTH- ACAZUNIP
MONILLA AMENA
MONOCHOA
MONTAÑA DE FUEGO
MONTAÑITA
MONTEFRIO
MONTEGRANDE
MONTERREY
MONZHOMANDO
MORA ALEMANIA
MORELIA
MORICHAL
MORICHALITO
MORICHITO
MORRO HERMOSO
MORROY
MOUWASIRA
MUE
MUELLAMUES
MUINANE
MUISCA
MUISCA DE BOSA
MUISCA DE SUBA
MULIATUY
MURAL
MURALEN
MURRALEN SECTOR MUSICHI
MURRENAMANA
MURUI_UITOTO
MURUTINGA-ZONA  OZCIMI
MUSAMANA
MUSHALERRAIN
MUSICHI
MUSSE UKWE
MUSU WAIRA SACHA NUCANCHIPA
MUSURRUNACUNA
MUSURUNAKUNA
MUTANACUA ZONA ACTIVA
NAM MISAK
NAMONASHITOU
NANA-ZONA ASATRIBVA
NANURCO
NARANJALES
NAS
NASA CHACHA - NASA CHXCHX
NASA CHAMB
NASA KIWE
NASA KIWE ALTO SINAI
NASA KWE'SX TATA WALA
NASA SA´TAMA LUUÇXWE´SX (HIJOS DE JUAN TAMA)
NASA THA
NASA UH
NASA YU'KHZXICXKWE-SELVA HERMOSA
NASAPAEZ
NASA_PAEZ
NASA_PAÉZ
NATACOY PIJAO
NATAIMA
NATAROCO
NAUNASHITOU
NAVARRO BONILLA ZONA OZCIMI
NAZARETH
NAZARETH DEL TI ZONA AATIVAM
NEW WITTEMBERG
NICOLAS RAMIREZ
NIMAIRA NAIMEKI IBIRI KM 11
NOVIRAO
NUEVA ARGELIA
NUEVA COLOMBIA
NUEVA ESPERANZA
NUEVA ESTACION
NUEVA ESTRELLA
NUEVA FLORIDA-ZONA AATIVAM
NUEVA FORTUNA
NUEVA ISLA
NUEVA PALESTINA
NUEVA REFORMA (ANTES PUERTO FARAON)
NUEVA UNION
NUEVA VICTORIA
NUEVA VIDA
NUEVO AMANECER LA MESETA
NUEVO AMANECER MAME ÑA´TA UMUGUSE
NUEVO CAMPO ALEGRE
NUEVO HORIENTE
NUEVO HORIZONTE
NUEVO JARDIN
NUEVO ORIENTE
NUEVO PARAISO LA BALASTRERA
NUEVO PORVENIR DE RETIRO NUEVO
NUEVO PUEBLO -ACAZUNIP
NUKAK
NUKANCHIPA ALPHA
NUKANCHIPA IUKASKA
NUKANCHIPA LLAKTA
NUKANCHIRUNA
NUNALBI ALTO ULBI
NUTABE
OBONUCO
OCIM
OCOMATIRRA SECTOR BAHIA HONDA
OKAINA
OLINDA PAPURI  - ACAZUNIP
OLIRCO
OLOKOMANA (OLOCOMANA)
OLONOKIOU
ONDAS DEL CAFRE
ORITO SIBERIA VALLE DEL GUAMUEZ
ORITO-SIBERIA-VALLE DEL GUAMUEZ
OROBAJO
OROCHONKAL
ORROKO
ORROTCHON
OTONMUIN-CARRIZAL
OVEJAS SIBERIA
PABLO MUERA
PACANDE
PACLIMANA
PAEZ DE GAITANIA
PAEZ JERUSALEN
PAJARO SOCORRIAL
PAJONAL
PAKIMANA
PALAJULEEN
PALASUMANA
PALEMSKA
PALENSO
PALEPALEN
PALERMO
PALESTINA
PALETARA
PALMA ALTA
PALMAR BOCAS DE BABI
PALMAR BRILLANTE
PALMARITO
PALMAS
PALMAS VERDES
PALMERAS
PALMIRA ALTA
PALMITAL
PALMITO SUR
PALOMEKO
PALONEGRO
PALVI GUALTAL
PANCHO
PANSEÑOR
PANTERRAMANA
PAPAYO
PARAISO (SECTOR BAHIA HONDA)
PARAISO CLAN PUSHAINA
PARAISO INTEGRAL
PARAISO PLAZA BONITA
PARAJAIN (PARALAIN)
PARAJIMARU SECTOR PUERTO LOPEZ CORREGIMIENTO PUERTO LOPEZ
PARANTARUM
PARRITCHON (PARRITCHAN)
PARRITKAD
PARRULUAMANA
PASIPAMANA
PASOANCHO
PASTO
PASTOS -ARMENIA-QUINDIO
PASTOS ORO VERDE
PATAJATAMANA
PATARRIAL
PATH YU
PATIO BONITO NORTE
PATIO BONITO SUR
PATRULLERO
PATSUA
PATSUARRALI
PATTAIN
PAUJIL
PAÑARRER
PERA`A
PEREIRA
PERRAKAT (PERRACAT)
PESCADITO ZONA 2
PESUAPA
PES_AL_
PESÜALÜ
PETACA
PETPANACHON
PETSUAPA (PEZUAPA) PESUWAPA
PEZ DE CORINTO (LOPEZ ADENTRO)
PEÑA BLANCA
PEÑA INDIA
PEÑA ROJA
PEÑABLANCA
PIAJO
PIAPOCO
PIAROA
PIAZAPA
PIBI PAI
PICA PICA NUEVO
PICHIMA QUEBRADA
PIEDRA ALTA
PIEDRA SAGRADA LA GRAN FAMILIA DE LOS PASTOS
PIEDRA SELLADA  QUEBRADA TRONQUERA
PIEDRAS BLANCAS
PIGUAMBI PALANGALA
PIJAO
PIJAO DE ORO
PIJAO EL VERGEL
PIJAO LA SIERRITA
PIJAOS DE CUNIRCO
PIJAOS LOS LAURELES
PIJIGUAY
PIMENTAL
PIOULEKAT
PIPALTA-PALBI  YAGUAPI
PIPAMANA
PIRACEMO- ZONA UDIC
PIRACUARA-ZONA ACAZUNIP
PIRAMIRI -  ZONA UDIC
PIRATAPUYO
PIRRUWAITAMANA
PISHIAO
PISHIRRU
PITAL DE MEGUA
PITSHUSHAMANA
PIYUSHIPANA
PLANADAS DE TELEMBI
PLAYA BLANCA
PLAYAS DE BOJABA
PLAYITA
PLAYON
PLAYON NASA NAYA
PLAZA BONITA
PLAZA BONITA CUATRO CAMINOS
POCARA
POCHARCO
POINCOS TAIRA
POLICARPA
POLINDARA
POLUMOU
POLVILLO
POPORTIN
POPOYA
POR DEFINIR
PORCHINA
POROPO CORREGIMIENTO BAHIA HONDA
PORUJARI
PORVENIR
POTORKISHIMANA
POTRERITO
POTRERITO SAN MARTIN
POTRERITO-DOYARE
PROSPERIDA
PROVIDENCIA
PROVIDENCIA NUEVA
PROVIDENCIA SUR
PUCARON-ZONA AATIVAM
PUEBLECITO
PUEBLECITO SUR
PUEBLO NUEVO
PUEBLO NUEVO CERAL
PUEBLO NUEVO-ZONA AATICAM
PUEBLO VIEJO DE SANTA RITA LA MINA
PUENTE URE
PUERTA DEL MACIZO
PUERTO -EQUE
PUERTO ANTIOQUIA-ZONA ASATRIBVA
PUERTO ASIS (AVIYU) -ZONA ASATRIBVA
PUERTO BELEN
PUERTO CAIMAN
PUERTO CASANARE-ZONA UDIC
PUERTO CASTAÑO
PUERTO COLOMBIA
PUERTO COLOMBIA - ASATRAIYUVA
PUERTO COLOMBIA TIQUIE -ZONA AATIZOT
PUERTO COLON-ZONA ASATRIBVA
PUERTO CORDOBA
PUERTO CORRONCHO-ZONA OZCIMI
PUERTO ESPERANZA
PUERTO ESPERANZA-AATICAM
PUERTO ESTRELLA
PUERTO GALVE
PUERTO HUILA
PUERTO LIBRE
PUERTO LIMON
PUERTO LIMON - ZONA AATIVAM
PUERTO LLERAS -ZONA ASATIQ
PUERTO LOMA -ASATRAIYUVA
PUERTO LOPEZ - ZONA UDIC
PUERTO LORO - ZONA AATIZOT
PUERTO MOLANO
PUERTO MONFORT
PUERTO NARE
PUERTO NARIÑO
PUERTO NARIÑO  -ZONA ASATRIZY
PUERTO NUEVO
PUERTO PALOMA-ZONA AATICAM
PUERTO PINILLA -ASATRIBVA
PUERTO PUNTALES
PUERTO PUPUÑA-ZONA AATIVAM
PUERTO REFUGIO
PUERTO SAMARIA
PUERTO TEJADA
PUERTO TRIUNFO
PUERTO VAUPES-ZONA OZCIMI
PUERTO VIEJO
PUERTO ÑEQUE
PUETTALUA
PUIKAT
PUINAVE
PULGANDE CAMPOALEGRE
PUNTA TIGRE
PUNTA VERDE
PUPUÑA

In [88]:
# Se crea una lista de los valores únicos de la columna nombre_del_grupo_etnico
ethnic_list = data_covid['nombre_del_grupo_etnico'].unique()

# Se crea una lista con los nombres de los grupos etnicos a corregir
wrong_ethnic = ['Sin comunidad', 'SIn comunidad', 'Sin Comunidad', 'Sin comunidad', '1', 'E', 'HEREDEROS DE TABACO COCA Y YUCA DULCE CIHTACOYD P + + NE ABYEJU + JTSAMEI', 'JAtENI DtONA PORTAL FRAGUITA', 'LA  SOLEDAD', 'NASA_PAEZ', 'NASA_PAÉZ', 'PES_AL_', 'QUI', 'Por definir', 'WA', 'URRAICHY', 'UAI+MA', 'iNGA', 'sikuani', 'wayuu']

# Se crea una lista con los nombres de los grupos etnicos correctos
right_ethnic = ['SIN COMUNIDAD', 'SIN COMUNIDAD', 'SIN COMUNIDAD', 'SIN COMUNIDAD', 'SIN COMUNIDAD', 'SIN COMUNIDAD', 'HEREDEROS DE TABACO COCA Y YUCA DULCE CIHTACOYD ABYEJU JTSAMEI', 'JATENI DTONA PORTAL FRAGUITA', 'LA SOLEDAD', 'NASAPAEZ', 'NASAPAEZ', 'PESÜALÜ', 'SIN COMUNIDAD', 'SIN COMUNIDAD', 'SIN COMUNIDAD', 'URRAICHI', 'UAIMA', 'INGA', 'SIKUANI', 'WAYUU']

# Se crea la lista vacía que contendrá los valores correctos
new_ethnic_list = []

# Se realiza la iteración de las listas para llenar la lista que contendrá los valores correctos
for ethnic in ethnic_list:
    if ethnic in wrong_ethnic:
        new_ethnic_list.append(right_ethnic[wrong_ethnic.index(ethnic)])
    else:
        new_ethnic_list.append(ethnic)

# Se crea el diccionario entre la lista de grupos etnicos y su respectiva transfomación
ethnic_dictionary = dict(zip(ethnic_list, new_ethnic_list))

# Se realiza el mapeo del diccionario en el df
data_covid['nombre_del_grupo_etnico'] = data_covid['nombre_del_grupo_etnico'].map(ethnic_dictionary)

# Se imprime el conteo de valores
data_covid['nombre_del_grupo_etnico'].value_counts(dropna=False)

nombre_del_grupo_etnico
NaN                                                    6307107
SIN COMUNIDAD                                            29387
ZENU                                                      9264
PIJAO                                                     4112
WAYUU                                                     2813
                                                        ...
COTORRERA-UASPAJURE-SARRUTPANA  ZONA DE WAIMPIRALEN          1
COROZAL                                                      1
PUERTO NARIÑO  -ZONA ASATRIZY                                1
COROCITO                                                     1
MASHALERRAIN                                                 1
Name: count, Length: 1874, dtype: int64

In [89]:
# Se remplazan los valores nulos por SIN COMUNIDAD
data_covid['nombre_del_grupo_etnico'] = data_covid['nombre_del_grupo_etnico'].fillna('SIN COMUNIDAD')

# Se imprime el conteo de valores
data_covid['nombre_del_grupo_etnico'].value_counts(dropna=False)

nombre_del_grupo_etnico
SIN COMUNIDAD                                          6336494
ZENU                                                      9264
PIJAO                                                     4112
WAYUU                                                     2813
PASTO                                                     2764
                                                        ...
COTORRERA-UASPAJURE-SARRUTPANA  ZONA DE WAIMPIRALEN          1
COROZAL                                                      1
PUERTO NARIÑO  -ZONA ASATRIZY                                1
COROCITO                                                     1
MASHALERRAIN                                                 1
Name: count, Length: 1873, dtype: int64

<h3>
    Limpieza de datos de la columna nombre_municipio
</h3>

In [90]:
# Visualización de los valores unicos de la columna nombre_municipio
data_covid['nombre_municipio'].value_counts(dropna=False)

nombre_municipio
BOGOTA          1888137
MEDELLIN         550790
CALI             406751
BARRANQUILLA     277989
CARTAGENA        163526
                 ...
VillaGarzon           1
Soacha                1
ENTRERrIOS            1
Somondoco             1
Gameza                1
Name: count, Length: 1057, dtype: int64

In [91]:
# Se define una lista con la cantidad de valores únicos de la columna nombre_municipio
list_municipalities = list(data_covid['nombre_municipio'].unique())

# Lista vacía que contendrá los valores únicos en mayúscula
upper_municipalities = []

# Iteración de los municipios, transformación a mayúscula y agregación a la lista vacía
for municipality in list_municipalities:
    upper_municipalities.append(municipality.upper())

# Se crea el diccionario entre los municipios y su respectiva transfomación a mayúsculas
municipality_dictionary = dict(zip(list_municipalities, upper_municipalities))

# Se realiza el mapeo del diccionario en el df
data_covid['nombre_municipio'] = data_covid['nombre_municipio'].map(municipality_dictionary)

# Se imprime el conteo de valores
data_covid['nombre_municipio'].value_counts(dropna=False)

nombre_municipio
BOGOTA                            1888137
MEDELLIN                           550794
CALI                               406751
BARRANQUILLA                       277989
CARTAGENA                          163526
                                   ...
PUERTO ALEGRIA (CD)                     7
EL ENCANTO (CD)                         7
BELEN DE BAJIRA                         4
PAPUNAUA (MORICHAL) (CD)                1
MORICHAL (MORICHAL NUEVO) (CD)          1
Name: count, Length: 1039, dtype: int64

<h3>
    Limpieza de datos de la columna nombre_departamento
</h3>

In [92]:
# Visualización de los valores unicos de la columna nombre_departamento
data_covid['nombre_departamento'].value_counts(dropna=False)

nombre_departamento
BOGOTA             1888137
ANTIOQUIA           955271
VALLE               572724
CUNDINAMARCA        331331
SANTANDER           297370
BARRANQUILLA        277989
CARTAGENA           163526
ATLANTICO           141072
BOYACA              131133
TOLIMA              127764
NORTE SANTANDER     126015
CORDOBA             123095
CALDAS              120029
RISARALDA           110235
CESAR               109830
NARIÑO              108967
META                108194
HUILA               103578
STA MARTA D.E.       84863
CAUCA                77337
QUINDIO              73290
SUCRE                67471
GUAJIRA              58353
CASANARE             43302
BOLIVAR              40336
MAGDALENA            33165
CAQUETA              25750
PUTUMAYO             22142
CHOCO                18907
ARAUCA               17387
SAN ANDRES           10402
AMAZONAS              7879
GUAVIARE              5692
VICHADA               3496
GUAINIA               2795
VAUPES                1972
Santander              162
Cundinamarca             7
Caldas                   1
Tolima                   1
Putumayo                 1
Name: count, dtype: int64

In [93]:
# Se define una lista con la cantidad de valores únicos de la columna nombre_departamento
list_departments = list(data_covid['nombre_departamento'].unique())

# Lista vacía que contendrá los valores únicos en mayúscula
upper_departments = []

# Iteración de los departamentos, transformación a mayúscula y agregación a la lista vacía
for department in list_departments:
    upper_departments.append(department.upper())

# Se crea el diccionario entre los departamentos y su respectiva transfomación a mayúsculas
department_dictionary = dict(zip(list_departments, upper_departments))

# Se realiza el mapeo del diccionario en el df
data_covid['nombre_departamento'] = data_covid['nombre_departamento'].map(department_dictionary)

# Se imprime el conteo de valores
data_covid['nombre_departamento'].value_counts(dropna=False)

nombre_departamento
BOGOTA             1888137
ANTIOQUIA           955271
VALLE               572724
CUNDINAMARCA        331338
SANTANDER           297532
BARRANQUILLA        277989
CARTAGENA           163526
ATLANTICO           141072
BOYACA              131133
TOLIMA              127765
NORTE SANTANDER     126015
CORDOBA             123095
CALDAS              120030
RISARALDA           110235
CESAR               109830
NARIÑO              108967
META                108194
HUILA               103578
STA MARTA D.E.       84863
CAUCA                77337
QUINDIO              73290
SUCRE                67471
GUAJIRA              58353
CASANARE             43302
BOLIVAR              40336
MAGDALENA            33165
CAQUETA              25750
PUTUMAYO             22143
CHOCO                18907
ARAUCA               17387
SAN ANDRES           10402
AMAZONAS              7879
GUAVIARE              5692
VICHADA               3496
GUAINIA               2795
VAUPES                1972
Name: count, dtype: int64

<h3>
    Limpieza de datos de la columna ubicacion_del_caso
</h3>

In [94]:
# Visualización de los valores unicos de la columna nombre_departamento
data_covid['ubicacion_del_caso'].value_counts(dropna=False)

ubicacion_del_caso
Casa            6177081
Fallecido        143125
NaN               41268
casa              28328
Hospital           1056
Hospital UCI        106
CASA                  7
Name: count, dtype: int64

In [95]:
# Se llenan los datos faltantes con FALLECIDO NO COVID
data_covid['ubicacion_del_caso'] = data_covid['ubicacion_del_caso'].fillna('FALLECIDO NO COVID')

data_covid['ubicacion_del_caso'].value_counts(dropna=False)

ubicacion_del_caso
Casa                  6177081
Fallecido              143125
FALLECIDO NO COVID      41268
casa                    28328
Hospital                 1056
Hospital UCI              106
CASA                        7
Name: count, dtype: int64

In [96]:
# Se define una lista con la cantidad de valores únicos de la columna ubicacion_del_caso
list_locations = list(data_covid['ubicacion_del_caso'].unique())

# Lista vacía que contendrá los valores únicos en mayúscula
upper_locations = []

# Iteración de las ubicaciones, transformación a mayúscula y agregación a la lista vacía
for location in list_locations:
    upper_locations.append(location.upper())

# Se crea el diccionario entre las ubicaciones y su respectiva transfomación a mayúsculas
location_dictionary = dict(zip(list_locations, upper_locations))

# Se realiza el mapeo del diccionario en el df
data_covid['ubicacion_del_caso'] = data_covid['ubicacion_del_caso'].map(location_dictionary)

# Se imprime el conteo de valores
data_covid['ubicacion_del_caso'].value_counts(dropna=False)

ubicacion_del_caso
CASA                  6205416
FALLECIDO              143125
FALLECIDO NO COVID      41268
HOSPITAL                 1056
HOSPITAL UCI              106
Name: count, dtype: int64

<h3>
    Limpieza de datos de la columna recuperado
</h3>

In [97]:
# Visualización de los valores unicos de la columna recuperado
data_covid['recuperado'].value_counts(dropna=False)

recuperado
Recuperado    6208573
Fallecido      142830
NaN             36327
Activo           2946
fallecido         295
Name: count, dtype: int64

In [98]:
# Se llenan los datos faltantes con FALLECIDO NO COVID
data_covid['recuperado'] = data_covid['ubicacion_del_caso'].fillna('FALLECIDO NO COVID')

data_covid['recuperado'].value_counts(dropna=False)

recuperado
CASA                  6205416
FALLECIDO              143125
FALLECIDO NO COVID      41268
HOSPITAL                 1056
HOSPITAL UCI              106
Name: count, dtype: int64

In [99]:
# Se define una lista con la cantidad de valores únicos de la columna recuperado
list_recovered = list(data_covid['recuperado'].unique())

# Lista vacía que contendrá los valores únicos en mayúscula
upper_recovered = []

# Iteración de los recuperados, transformación a mayúscula y agregación a la lista vacía
for recovered in list_recovered:
    upper_recovered.append(recovered.upper())

# Se crea el diccionario entre los recuperados y su respectiva transfomación a mayúsculas
recovered_dictionary = dict(zip(list_recovered, upper_recovered))

# Se realiza el mapeo del diccionario en el df
data_covid['recuperado'] = data_covid['recuperado'].map(recovered_dictionary)

# Se imprime el conteo de valores
data_covid['recuperado'].value_counts(dropna=False)

recuperado
CASA                  6205416
FALLECIDO              143125
FALLECIDO NO COVID      41268
HOSPITAL                 1056
HOSPITAL UCI              106
Name: count, dtype: int64

<h3>
    Limpieza de datos de la columna unidad_de_medida_de_edad
</h3>

In [100]:
# Visualización de los valores unicos de la columna unidad_de_medida_de_edad
data_covid['unidad_de_medida_de_edad'].value_counts(dropna=False)

unidad_de_medida_de_edad
1    6357475
2      30732
3       2762
5          1
4          1
Name: count, dtype: int64

In [101]:
# Ver las filas donde la unidad de medida es 4 o 5
errores_unidad = data_covid[data_covid['unidad_de_medida_de_edad'].isin([4, 5])]
errores_unidad[['edad', 'unidad_de_medida_de_edad']]

         edad  unidad_de_medida_de_edad
5233861     1                         5
5286388     9                         4

In [102]:
# Reemplazamos los valores atípicos 4 y 5 por 1 (Años), ya que, no se puede definir si son días, meses o años, se deja el año por defecto
data_covid['unidad_de_medida_de_edad'] = data_covid['unidad_de_medida_de_edad'].replace({4: 1, 5: 1})

data_covid['unidad_de_medida_de_edad'].value_counts(dropna=False)

unidad_de_medida_de_edad
1    6357477
2      30732
3       2762
Name: count, dtype: int64

<h3>
    Eliminación de las variables
</h3>

In [103]:
# Eliminación de las columnas solicitadas
del data_covid['codigo_divipola_departamento']
del data_covid['codigo_iso_del_pais']
del data_covid['codigo_divipola_municipio']

<h3>
    Copia del DF
</h3>

In [104]:
# Se crea la copia
data_covid_clean = data_covid.copy()

data_covid_clean.head()

,fecha_reporte_web,id_de_caso,fecha_de_notificacion,nombre_departamento,nombre_municipio,edad,unidad_de_medida_de_edad,sexo,tipo_de_contagio,ubicacion_del_caso,estado,nombre_del_pais,recuperado,fecha_de_inicio_de_sintomas,fecha_de_muerte,fecha_de_diagnostico,fecha_de_recuperacion,tipo_de_recuperacion,nombre_del_grupo_etnico,nombre_pertenencia_etnica
0,2020-12-24 00:00:00,"1,556,979",2020-12-22 00:00:00,VALLE,CALI,67,1,F,COMUNITARIA,CASA,LEVE,COLOMBIA,CASA,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,TIEMPO,SIN COMUNIDAD,OTRO
1,2020-12-24 00:00:00,"1,556,980",2020-12-19 00:00:00,VALLE,CALI,66,1,F,COMUNITARIA,CASA,LEVE,COLOMBIA,CASA,2020-12-07 00:00:00,NaN,2020-12-23 00:00:00,2020-12-25 00:00:00,TIEMPO,SIN COMUNIDAD,OTRO
2,2020-12-24 00:00:00,"1,556,981",2020-12-19 00:00:00,VALLE,CALI,68,1,F,COMUNITARIA,CASA,LEVE,COLOMBIA,CASA,2020-12-18 00:00:00,NaN,2020-12-22 00:00:00,2021-01-01 00:00:00,TIEMPO,SIN COMUNIDAD,OTRO
3,2020-12-24 00:00:00,"1,556,982",2020-12-22 00:00:00,VALLE,CALI,74,1,F,COMUNITARIA,FALLECIDO,FALLECIDO,COLOMBIA,FALLECIDO,2020-12-17 00:00:00,2020-12-30 00:00:00,2020-12-23 00:00:00,NaN,NO RECUPERADO,SIN COMUNIDAD,OTRO
4,2020-12-24 00:00:00,"1,556,983",2020-12-22 00:00:00,VALLE,CALI,65,1,F,COMUNITARIA,CASA,LEVE,COLOMBIA,CASA,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,TIEMPO,SIN COMUNIDAD,OTRO

<h3>
    Registros duplicados
</h3>

In [105]:
data_covid_clean.duplicated().sum()

np.int64(0)

<h3>
    Valores atípicos
</h3>

In [106]:
# Calcula el Primer Cuartil (Q1): el valor por debajo del cual se encuentra el 25% de las edades más bajas
Q1 = data_covid_clean['edad'].quantile(0.25)

# Calcula el Tercer Cuartil (Q3): el valor por debajo del cual se encuentra el 75% de las edades
Q3 = data_covid_clean['edad'].quantile(0.75)

# Calcula el Rango Intercuartílico (IQR): la diferencia entre Q3 y Q1. Representa el 50% central de los datos
IQR = Q3 - Q1

# Establece el límite inferior. Toda edad menor a este número se considerará un dato atípico (excesivamente joven/error)
lower_bound = Q1 - 1.5 * IQR

# Establece el límite superior. Toda edad mayor a este número se considerará un dato atípico (excesivamente mayor/error)
upper_bound = Q3 + 1.5 * IQR

# Filtra el df para aislar las filas donde la edad es menor al límite inferior o mayor al límite superior
outliers = data_covid_clean[(data_covid_clean['edad'] < lower_bound) | (data_covid_clean['edad'] > upper_bound)]

print(f'Número de datos atípicos de la columna edad: {len(outliers)}\n')

print(f'Porcentaje de datos atípicos de la columna edad: {(len(outliers) / len(data_covid_clean)) * 100:.2f}%\n')

print('Datos atípicos de la columna edad:\n')

# Muestra un resumen estadístico (media, min, max, etc.) de la columna edad
data_covid_clean['edad'].describe().round(2)

Número de datos atípicos de la columna edad: 14978

Porcentaje de datos atípicos de la columna edad: 0.23%

Datos atípicos de la columna edad:

count    6390971.00
mean          39.98
std           18.47
min            1.00
25%           27.00
50%           38.00
75%           53.00
max          114.00
Name: edad, dtype: float64

In [107]:
# Aplica la técnica de "Recorte" (Clipping). En lugar de borrar las filas atípicas, 
# reemplaza las edades extremas con el valor exacto de los límites que calculamos anteriormente
data_covid_clean['edad'] = data_covid_clean['edad'].clip(lower=lower_bound, upper=upper_bound)

# Muestra el resumen estadístico después del recorte para verificar que los valores min y max ya no superan los límites.
data_covid_clean['edad'].describe().round(2)

count    6390971.00
mean          39.97
std           18.45
min            1.00
25%           27.00
50%           38.00
75%           53.00
max           92.00
Name: edad, dtype: float64

<h3>
    Transformación de la edad a años
</h3>

In [108]:
# Se transforman las edades en años que se almacenará en la columna edad_años
data_covid_clean['edad_años'] = data_covid_clean.apply(lambda row: 
    row['edad'] if row['unidad_de_medida_de_edad'] == 1 # Años
    else row['edad'] / 12 if row['unidad_de_medida_de_edad'] == 2 # Meses
    else row['edad'] / 365 if row['unidad_de_medida_de_edad'] == 3 # Días
    else row['edad'], axis=1 
)

#Se eliminan las columnas edad y unidad_de_medida_de_edad
del data_covid_clean['edad']
del data_covid_clean['unidad_de_medida_de_edad']

#Validamo el df con la edad estandarizada
data_covid_clean.head()

,fecha_reporte_web,id_de_caso,fecha_de_notificacion,nombre_departamento,nombre_municipio,sexo,tipo_de_contagio,ubicacion_del_caso,estado,nombre_del_pais,recuperado,fecha_de_inicio_de_sintomas,fecha_de_muerte,fecha_de_diagnostico,fecha_de_recuperacion,tipo_de_recuperacion,nombre_del_grupo_etnico,nombre_pertenencia_etnica,edad_años
0,2020-12-24 00:00:00,"1,556,979",2020-12-22 00:00:00,VALLE,CALI,F,COMUNITARIA,CASA,LEVE,COLOMBIA,CASA,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,TIEMPO,SIN COMUNIDAD,OTRO,67.0
1,2020-12-24 00:00:00,"1,556,980",2020-12-19 00:00:00,VALLE,CALI,F,COMUNITARIA,CASA,LEVE,COLOMBIA,CASA,2020-12-07 00:00:00,NaN,2020-12-23 00:00:00,2020-12-25 00:00:00,TIEMPO,SIN COMUNIDAD,OTRO,66.0
2,2020-12-24 00:00:00,"1,556,981",2020-12-19 00:00:00,VALLE,CALI,F,COMUNITARIA,CASA,LEVE,COLOMBIA,CASA,2020-12-18 00:00:00,NaN,2020-12-22 00:00:00,2021-01-01 00:00:00,TIEMPO,SIN COMUNIDAD,OTRO,68.0
3,2020-12-24 00:00:00,"1,556,982",2020-12-22 00:00:00,VALLE,CALI,F,COMUNITARIA,FALLECIDO,FALLECIDO,COLOMBIA,FALLECIDO,2020-12-17 00:00:00,2020-12-30 00:00:00,2020-12-23 00:00:00,NaN,NO RECUPERADO,SIN COMUNIDAD,OTRO,74.0
4,2020-12-24 00:00:00,"1,556,983",2020-12-22 00:00:00,VALLE,CALI,F,COMUNITARIA,CASA,LEVE,COLOMBIA,CASA,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,TIEMPO,SIN COMUNIDAD,OTRO,65.0

In [109]:
# Muestra la descripción estadística de la nueva columna
data_covid_clean['edad_años'].describe().round(2)

count    6390971.00
mean          39.94
std           18.51
min            0.00
25%           27.00
50%           38.00
75%           53.00
max           92.00
Name: edad_años, dtype: float64

<h3>
    Decodificación de las columnas fechas
</h3>

In [110]:
# Se define la lista con el nombre de las columnas que tienen información de fechas
columns_date = ['fecha_reporte_web', 'fecha_de_notificacion', 'fecha_de_inicio_de_sintomas', 'fecha_de_muerte', 'fecha_de_diagnostico', 'fecha_de_recuperacion']

# Transformación de las columnas a formato datetime
for column in columns_date:
    if column in data_covid_clean.columns:
        data_covid_clean[column] = pd.to_datetime(data_covid_clean[column], errors='coerce')

data_covid_clean.head()

,fecha_reporte_web,id_de_caso,fecha_de_notificacion,nombre_departamento,nombre_municipio,sexo,tipo_de_contagio,ubicacion_del_caso,estado,nombre_del_pais,recuperado,fecha_de_inicio_de_sintomas,fecha_de_muerte,fecha_de_diagnostico,fecha_de_recuperacion,tipo_de_recuperacion,nombre_del_grupo_etnico,nombre_pertenencia_etnica,edad_años
0,2020-12-24,"1,556,979",2020-12-22,VALLE,CALI,F,COMUNITARIA,CASA,LEVE,COLOMBIA,CASA,2020-12-21,NaT,2020-12-23,2021-01-04,TIEMPO,SIN COMUNIDAD,OTRO,67.0
1,2020-12-24,"1,556,980",2020-12-19,VALLE,CALI,F,COMUNITARIA,CASA,LEVE,COLOMBIA,CASA,2020-12-07,NaT,2020-12-23,2020-12-25,TIEMPO,SIN COMUNIDAD,OTRO,66.0
2,2020-12-24,"1,556,981",2020-12-19,VALLE,CALI,F,COMUNITARIA,CASA,LEVE,COLOMBIA,CASA,2020-12-18,NaT,2020-12-22,2021-01-01,TIEMPO,SIN COMUNIDAD,OTRO,68.0
3,2020-12-24,"1,556,982",2020-12-22,VALLE,CALI,F,COMUNITARIA,FALLECIDO,FALLECIDO,COLOMBIA,FALLECIDO,2020-12-17,2020-12-30,2020-12-23,NaT,NO RECUPERADO,SIN COMUNIDAD,OTRO,74.0
4,2020-12-24,"1,556,983",2020-12-22,VALLE,CALI,F,COMUNITARIA,CASA,LEVE,COLOMBIA,CASA,2020-12-21,NaT,2020-12-23,2021-01-04,TIEMPO,SIN COMUNIDAD,OTRO,65.0

In [111]:
# Se procede a crear las tablas que contengan los datos del año y mes por separados
# Lista de columnas para el año
columns_year = ['año_reporte_web', 'año_notificaion', 'año_inicio_sintomas', 'año_muerte', 'año_diagnostico', 'año_recuperacion']

# Lista de columnas para el mes
columns_month = ['mes_reporte_web', 'mes_notificacion', 'mes_inicio_sintomas', 'mes_muerte', 'mes_diagnostico', 'mes_recuperacion']

# Se recorren las listas para asignar el valor correspondiente a cada columna
for index, column in enumerate(columns_date):
    if column in data_covid_clean.columns:
        data_covid_clean[columns_year[index]] = data_covid_clean[column].dt.year
        data_covid_clean[columns_month[index]] = data_covid_clean[column].dt.month

# Visualización de los datos
data_covid_clean.head()

,fecha_reporte_web,id_de_caso,fecha_de_notificacion,nombre_departamento,nombre_municipio,sexo,tipo_de_contagio,ubicacion_del_caso,estado,nombre_del_pais,...,año_notificaion,mes_notificacion,año_inicio_sintomas,mes_inicio_sintomas,año_muerte,mes_muerte,año_diagnostico,mes_diagnostico,año_recuperacion,mes_recuperacion
0,2020-12-24,"1,556,979",2020-12-22,VALLE,CALI,F,COMUNITARIA,CASA,LEVE,COLOMBIA,...,2020,12,2020.0,12.0,NaN,NaN,2020.0,12.0,2021.0,1.0
1,2020-12-24,"1,556,980",2020-12-19,VALLE,CALI,F,COMUNITARIA,CASA,LEVE,COLOMBIA,...,2020,12,2020.0,12.0,NaN,NaN,2020.0,12.0,2020.0,12.0
2,2020-12-24,"1,556,981",2020-12-19,VALLE,CALI,F,COMUNITARIA,CASA,LEVE,COLOMBIA,...,2020,12,2020.0,12.0,NaN,NaN,2020.0,12.0,2021.0,1.0
3,2020-12-24,"1,556,982",2020-12-22,VALLE,CALI,F,COMUNITARIA,FALLECIDO,FALLECIDO,COLOMBIA,...,2020,12,2020.0,12.0,2020.0,12.0,2020.0,12.0,NaN,NaN
4,2020-12-24,"1,556,983",2020-12-22,VALLE,CALI,F,COMUNITARIA,CASA,LEVE,COLOMBIA,...,2020,12,2020.0,12.0,NaN,NaN,2020.0,12.0,2021.0,1.0

<h3>
    Importación del df a un archivo .csv
</h3>

In [ ]:
# Nombre del archivo
filename = 'Casos_positivos_COVID-19_en_Colombia_limpios.csv'

# Se define el path
path = os.path.join(os.getcwd(), 'data', filename)

# Se guarda el archivo
data_covid_clean.to_csv(path, index=False)

<h3>
    Cantidad de fallecidos en Colombia mayores de 60 años
</h3>

In [113]:
# Se crea una variable que contenga los filtros requeridos
# Edad mayor de 60
# Que haya fallecido
deceased_colombia_over_60 = data_covid_clean[(data_covid_clean['edad_años'] > 60) & (data_covid_clean['recuperado'] == 'FALLECIDO')]

print(f'Cantidad de fallecidos en Colombia mayores de 60 años es: {len(deceased_colombia_over_60)}')

Cantidad de fallecidos en Colombia mayores de 60 años es: 102824

<h3>
    Cantidad de fallecidos en Antioquia mayores de 60 años
</h3>

In [114]:
# Se crea una variable que contenga los filtros requeridos
# Edad mayor de 60
# Que haya fallecido
# Que el departamento sea Antioquia
deceased_antioquia_over_60 = data_covid_clean[(data_covid_clean['edad_años'] > 60) & (data_covid_clean['recuperado'] == 'FALLECIDO') & (data_covid_clean['nombre_departamento'] == 'ANTIOQUIA')]

print(f'Cantidad de fallecidos en Antioquia mayores de 60 años es: {len(deceased_antioquia_over_60)}')

Cantidad de fallecidos en Antioquia mayores de 60 años es: 13827

<h3>
    Cantidad de fallecidos en Medellín mayores de 60 años
</h3>

In [115]:
# Se crea una variable que contenga los filtros requeridos
# Edad mayor de 60
# Que haya fallecido
# Que el municipio sea Medellín
deceased_medellin_over_60 = data_covid_clean[(data_covid_clean['edad_años'] > 60) & (data_covid_clean['recuperado'] == 'FALLECIDO') & (data_covid_clean['nombre_municipio'] == 'MEDELLIN')]

print(f'Cantidad de fallecidos en Antioquia mayores de 60 años es: {len(deceased_medellin_over_60)}')

Cantidad de fallecidos en Antioquia mayores de 60 años es: 7933

<h3>
    Tasa de letalidad en Colombia
</h3>

In [116]:
# Se define una variable que contendrá la información de los fallecidos
total_deaths = data_covid_clean[data_covid_clean['recuperado'] == 'FALLECIDO']

# Se define la variable con la cantidad de casos fallecidos
cant_total_deaths = len(total_deaths)

# Se define la variable con la cantidad del df
cant_cases = len(data_covid_clean)

# Se defien la fórmula de letalidad
fatality_rate_colombia = (cant_total_deaths / cant_cases) * 100

print(f'La tasa de letalidad del COVID-19 en Colombia es: {fatality_rate_colombia:.2f}%')

La tasa de letalidad del COVID-19 en Colombia es: 2.24%

<h3>
    Tasa de letalidad en Antioquia
</h3>

In [117]:
# Se define una variable que contendrá la información de los casos en Antioquia
cases_antioquia = data_covid_clean[data_covid_clean['nombre_departamento'] == 'ANTIOQUIA']

# Se define la variable con la cantidad de casos de Antioquia
cant_cases_antioquia = len(cases_antioquia)

# Se define la variable que contendrá los fallecidos en Antioquia
deaths_antioquia = cases_antioquia[cases_antioquia['recuperado'] == 'FALLECIDO']

# Se define la variable que contendrá la cantidad de fallecidos en Antioquia
cant_death_antioquia = len(deaths_antioquia)

# Se defien la fórmula de letalidad
fatality_rate_antioquia = (cant_death_antioquia / cant_cases_antioquia) * 100

print(f'La tasa de letalidad del COVID-19 en Antioquia es: {fatality_rate_antioquia:.2f}%')

La tasa de letalidad del COVID-19 en Antioquia es: 1.96%

<h3>
    Tasa de letalidad en Medellín
</h3>

In [118]:
# Se define una variable que contendrá la información de los casos en Medellín
cases_medellin = data_covid_clean[data_covid_clean['nombre_municipio'] == 'MEDELLIN']

# Se define la variable con la cantidad de casos de Medellín
cant_cases_medellin = len(cases_medellin)

# Se define la variable que contendrá los fallecidos en Medellín
deaths_medellin = cases_medellin[cases_medellin['recuperado'] == 'FALLECIDO']

# Se define la variable que contendrá la cantidad de fallecidos en Medellín
cant_death_medellin = len(deaths_medellin)

# Se defien la fórmula de letalidad
fatality_rate_medellin = (cant_death_medellin / cant_cases_medellin) * 100

print(f'La tasa de letalidad del COVID-19 en Medellín es: {fatality_rate_antioquia:.2f}%')

La tasa de letalidad del COVID-19 en Medellín es: 1.96%

<h3>
    Retraso promedio entre fecha_de_diagnostico y fecha_de_inicio_de_sintomas
</h3>

In [119]:
# Restamos las dos fechas que deseamos revisar
diference_between_diagnosis_symptoms = data_covid_clean['fecha_de_diagnostico'] - data_covid_clean['fecha_de_inicio_de_sintomas']

# Se extrae solo el número de días y se calcula el promedio
average_delay = diference_between_diagnosis_symptoms.dt.days.mean()

print(f'El retraso promedio entre síntomas y diagnóstico es de: {average_delay:.1f} días')

El retraso promedio entre síntomas y diagnóstico es de: 8.4 días

<h3>
    Retraso promedio entre fecha_reporte_web y fecha_de_diagnostico
</h3>

In [120]:
# Restamos las dos fechas que deseamos revisar
diference_between_diagnosis_symptoms = data_covid_clean['fecha_reporte_web'] - data_covid_clean['fecha_de_diagnostico']

# Se extrae solo el número de días y se calcula el promedio
average_delay = diference_between_diagnosis_symptoms.dt.days.mean()

print(f'El retraso promedio entre el reporte web y diagnóstico es de: {average_delay:.1f} días')

El retraso promedio entre el reporte web y diagnóstico es de: 4.4 días

<h3>
    Retraso promedio entre fecha_de_recuperacion y fecha_de_inicio_de_sintomas
</h3>

In [121]:
# Restamos las dos fechas que deseamos revisar
diference_between_diagnosis_symptoms = data_covid_clean['fecha_de_recuperacion'] - data_covid_clean['fecha_de_inicio_de_sintomas']

# Se extrae solo el número de días y se calcula el promedio
average_delay = diference_between_diagnosis_symptoms.dt.days.mean()

print(f'El retraso promedio entre recuperación e inicio de síntomas es de: {average_delay:.1f} días')

El retraso promedio entre recuperación e inicio de síntomas es de: 23.0 días

<h3>
    Retraso promedio entre fecha_de_muerte y fecha_de_inicio_de_sintomas
</h3>

In [122]:
# Restamos las dos fechas que deseamos revisar
diference_between_diagnosis_symptoms = data_covid_clean['fecha_de_muerte'] - data_covid_clean['fecha_de_inicio_de_sintomas']

# Se extrae solo el número de días y se calcula el promedio
average_delay = diference_between_diagnosis_symptoms.dt.days.mean()

print(f'El retraso promedio entre el fallecimiento y el inicio de los síntomas es de: {average_delay:.1f} días')

El retraso promedio entre el fallecimiento y el inicio de los síntomas es de: 44.8 días